// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuvID00DeG2CuuMbX6_BOgMETpIhqDqXo',
    appId: '1:402838160392:web:40f32009ed79dcf6547dbd',
    messagingSenderId: '402838160392',
    projectId: 'read-and-tell',
    authDomain: 'read-and-tell.firebaseapp.com',
    storageBucket: 'read-and-tell.firebasestorage.app',
    measurementId: 'G-HMN5CMYZJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2LY_no79tQsHXHrIw4_X-7cczIJNk64o',
    appId: '1:402838160392:android:49a113c9c3eb47ce547dbd',
    messagingSenderId: '402838160392',
    projectId: 'read-and-tell',
    storageBucket: 'read-and-tell.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtMOphcPB1A2wtzyRN3YV13mLsB1vfVRg',
    appId: '1:402838160392:ios:dbb097d8735352a2547dbd',
    messagingSenderId: '402838160392',
    projectId: 'read-and-tell',
    storageBucket: 'read-and-tell.firebasestorage.app',
    iosBundleId: 'com.example.projectBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtMOphcPB1A2wtzyRN3YV13mLsB1vfVRg',
    appId: '1:402838160392:ios:dbb097d8735352a2547dbd',
    messagingSenderId: '402838160392',
    projectId: 'read-and-tell',
    storageBucket: 'read-and-tell.firebasestorage.app',
    iosBundleId: 'com.example.projectBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuvID00DeG2CuuMbX6_BOgMETpIhqDqXo',
    appId: '1:402838160392:web:2fcebd94068e968a547dbd',
    messagingSenderId: '402838160392',
    projectId: 'read-and-tell',
    authDomain: 'read-and-tell.firebaseapp.com',
    storageBucket: 'read-and-tell.firebasestorage.app',
    measurementId: 'G-JT3J0XBZJ8',
  );
}
